### ISSUE TITLE
External interuppt

### ISSUE THREAD

**Issue by chefpro** [JorgeAparicio/libstm32pp#1]
Hi Jorge,
i saw your projects and tutorials. You are doing a very good job.
I have a question about external interuppt support.

I have written a small program that should controll a small power unit.
It will rule the carburetor with a small servo for holding the messured rpm constant.

I have the problem that the external interuppt is not triggering.

My dev is a stm32vldiscovery board.

What i have got (It is more, but this are the hot parts here):

<code>
typedef PA1 RPMPIN;
typedef EXTI1 RPMINT;

void initializeGpio()
{
  GPIOA::enableClock();

  RPMINT::enableHardwareInterruptByRisingEdge();
  RPMPIN::setMode(gpio::cr::INPUT_PULL_X);

}

void interrupt::EXTI1()
{
    RPMINT::clearPendingFlag();
}

</code>

I read in the spec that i have to set  the nvic and the interupt enabeled, but I can not see how to make that work with your libary.

I want to make it happen with internal pull-up.

So, what have i missed ?

If you help me here i will write an example and give that to your project if you want.

Thanks, Peter

**Comment by JorgeAparicio** [comment]
Hello Peter,

To make the EXTI work you need to do a few things:

1) Configure the GPIO pin as Alternate Function: setMode(gpio::cr::AF_OPEN_DRAIN_xxMHZ)
2) Put the GPIO pin in pull-up / pull-down: use the setPullUp() or setPullDown() functions
3) Map the EXTIn to your GPIO pin using the AFIO peripheral.
4) Unmask the EXTI interrupt using the NVIC peripheral.

(1) and (2) are straightforward. I've just made a commit that implements a function to do (3) and makes (4) easier.

I've also added a demo about the user button available on the STM32VLDISCOVERY: See /demo/vldiscovery/user_button.hpp.

Either pull or clone the last version, and refer to the demo.

Good luck with your project!

Jorge

P.S. Don't forget to tell me if it works!

**Comment by JorgeAparicio** [comment]
No further comment on this issue received. Closed.

**Comment by chefpro** [comment]
Hi JorgeAparicio,

sorry for the late response.
Yes, external interrupts work now.
I had not much time to develop this any further till now, but if i make any progress on this project i will write a small note.

Thanks, Peter
